#!/usr/bin/env ruby
require 'rafini/requires'
Rafini.requires'
  ruby        ~>3.1
  help_parser ~>8.0'

OPTIONS = HelpParser['',<<HELP]
Usage:
  urbandictionary <words=WORD>+
Types:
  WORD /^\\w+$/
# Note:
# If you get a "Found" message,
# try either the Capitalized or lower case term.
HELP

# I'm HTML scrapping via Nokogiri.
require 'nokogiri'
require 'web_api'

# The leading '/' is needed.
DICT = WebApi.new 'https://www.urbandictionary.com/'

# This creates method :define on
# https://www.urbandictionary.com/define.php'
DICT.add(:define, 'define.php')

# I'll be getting the HTML DOC from Nokogiri.
# I just want the first definition, if any.
# Be warned that HTML scrapping breaks easily on site changes.
def define(term)
  doc = DICT.define( {term: term} ).css('div.meaning')
  # <div class="meaning">
  if meaning = doc.css('div.meaning')&.first&.text
    return meaning
  end
  'N/A'
rescue
  $!.message
end

puts define OPTIONS.words.join(' ')
